export interface RPGEnemy {
  id: string;
  name: string;
  title: string;
  maxHp: number;
  hp: number;
  atk: number;
  def: number;
  spd: number;
  atb: number; // 0 to 100
  color: string;
  dead: boolean;
  actionTimer: number;
  startX: number;
  startY: number;
  x: number;
  y: number;
  isBoss?: boolean;
  bossCharge?: number;
  coinReward: number;
  element?: 'kinetic' | 'thermal' | 'cryo' | 'quantum' | 'glitch';
  loreDescription?: string;
  factionOrOrigin?: string;
  scrapDrop?: { materialId: string; name: string; count: number; chance: number };
}

export interface BestiaryRecord {
  id: string;
  name: string;
  title: string;
  icon: string;
  sector: string;
  element: 'kinetic' | 'thermal' | 'cryo' | 'quantum' | 'glitch';
  faction: string;
  baseHp: number;
  baseAtk: number;
  baseDef: number;
  spd: number;
  drops: string;
  weakness: string;
  description: string;
}

export const BESTIARY_DATA: BestiaryRecord[] = [
  // Sector 01
  {
    id: 'patrol_drone',
    name: 'Compliance Patrol Drone',
    title: 'Biometric Sentry',
    icon: '🛸',
    sector: 'Sector 01 (Neon Slums)',
    element: 'quantum',
    faction: 'The Algorithm Hegemony',
    baseHp: 130,
    baseAtk: 18,
    baseDef: 4,
    spd: 2.5,
    drops: '25 Coins, Scrapped Micro-Lens',
    weakness: 'Thermal (Overclock melting)',
    description: 'Autonomous floating security unit scanning alleyways for unsanctioned P2P bandwidth. Fires calibrated suppression pulses.',
  },
  {
    id: 'hegemony_enforcer',
    name: 'Hegemony Street Warden',
    title: 'Bureaucracy Shock-Troop',
    icon: '👮‍♂️⚡',
    sector: 'Sector 01 (Neon Slums)',
    element: 'kinetic',
    faction: 'The Algorithm Hegemony',
    baseHp: 210,
    baseAtk: 24,
    baseDef: 9,
    spd: 2.0,
    drops: '40 Coins, Riot Shield Plate',
    weakness: 'Glitch (Armor bypass)',
    description: 'Cybernetically augmented riot cop enforcing bandwidth curfew with hydraulic batons and electric stun cuffs.',
  },
  {
    id: 'latency_thief',
    name: 'Latency Pickpocket',
    title: 'Subway Phantom',
    icon: '👻⏱️',
    sector: 'Sector 01 (Neon Slums)',
    element: 'glitch',
    faction: 'The Latency Phantoms',
    baseHp: 150,
    baseAtk: 22,
    baseDef: 5,
    spd: 3.5,
    drops: '35 Coins, Stolen EMP Delay Coil',
    weakness: 'Kinetic (Physical stagger)',
    description: 'Stealth thief using delay coils to lag victims’ perception by three seconds before picking their cyberware pockets.',
  },
  {
    id: 'boss_agent_01',
    name: 'Agent 01',
    title: 'Compliance Director (Sector 01 Boss)',
    icon: '🕶️👔',
    sector: 'Sector 01 (Neon Slums)',
    element: 'quantum',
    faction: 'The Algorithm Hegemony',
    baseHp: 420,
    baseAtk: 28,
    baseDef: 12,
    spd: 3.0,
    drops: '80 Coins, Titanium Heatsink Relic',
    weakness: 'Glitch & Thermal',
    description: 'Reptilian bureaucrat in a tailor-made graphite suit. Commands tactical drone swarms and wields an electric monomolecular whip.',
  },

  // Sector 02
  {
    id: 'overclock_brawler',
    name: 'Overclocker Brawler',
    title: 'Street Marauder',
    icon: '🏍️🔥',
    sector: 'Sector 02 (The Silicon Sinks)',
    element: 'thermal',
    faction: 'The Overclockers',
    baseHp: 220,
    baseAtk: 26,
    baseDef: 7,
    spd: 2.8,
    drops: '35 Coins, Overclock Resistor',
    weakness: 'Cryo (Thermal shock)',
    description: 'Desert raider with bypassed voltage limiters. Attacks in a frenzied flurry of molten lead and exhaust flames.',
  },
  {
    id: 'scrap_golem',
    name: 'Scrap GPU Golem',
    title: 'Rusty Colossus',
    icon: '🗿⚙️',
    sector: 'Sector 02 (The Silicon Sinks)',
    element: 'kinetic',
    faction: 'Nomad Clans',
    baseHp: 400,
    baseAtk: 32,
    baseDef: 20,
    spd: 1.6,
    drops: '50 Coins, Pure Silicon Core',
    weakness: 'Glitch (Structural bypass)',
    description: 'A lumbering automaton cobbled together from hundreds of crushed heatsinks and burnt circuit boards.',
  },
  {
    id: 'sand_crawler',
    name: 'Copper Scavenger',
    title: 'Dune Crawler',
    icon: '🦂⚡',
    sector: 'Sector 02 (The Silicon Sinks)',
    element: 'thermal',
    faction: 'Wildlife / Scavengers',
    baseHp: 180,
    baseAtk: 28,
    baseDef: 8,
    spd: 3.2,
    drops: '30 Coins, Conductive Stinger',
    weakness: 'Cryo',
    description: 'Mechanical arachnid that burrows beneath the copper dunes, ambushing travelers to harvest raw thermal capacitors.',
  },
  {
    id: 'boss_overclock',
    name: 'Warlord Overclock',
    title: 'Desert Tyrant (Sector 02 Boss)',
    icon: '👑🏍️',
    sector: 'Sector 02 (The Silicon Sinks)',
    element: 'thermal',
    faction: 'The Overclockers',
    baseHp: 580,
    baseAtk: 38,
    baseDef: 15,
    spd: 3.4,
    drops: '120 Coins, Overclock Crystal Relic',
    weakness: 'Cryo & Quantum',
    description: 'Ruler of the Silicon Sinks. Drives a twin-turbocharged copper war-rig and unleashes superheated nitro explosions.',
  },

  // Sector 03
  {
    id: 'buffer_wraith',
    name: 'Buffer Wraith',
    title: 'Spectral Data Phantom',
    icon: '👻❄️',
    sector: 'Sector 03 (The Vapor Crypts)',
    element: 'cryo',
    faction: 'The Church of the Infinite Buffer',
    baseHp: 260,
    baseAtk: 34,
    baseDef: 9,
    spd: 3.4,
    drops: '45 Coins, Frozen Memory Cache',
    weakness: 'Thermal (Thawing flame)',
    description: 'Disembodied spirit of a user trapped in an infinite loading circle during Protocol Zero. Drains warmth and freezes ATB.',
  },
  {
    id: 'code_inquisitor',
    name: 'Code Inquisitor',
    title: 'Protocol Enforcer',
    icon: '⚖️📜',
    sector: 'Sector 03 (The Vapor Crypts)',
    element: 'quantum',
    faction: 'The Protocol Templars',
    baseHp: 380,
    baseAtk: 40,
    baseDef: 18,
    spd: 2.6,
    drops: '65 Coins, Ancient RFC Scroll',
    weakness: 'Glitch (Unparsed exception)',
    description: 'Zealous crusader who enforces rigid byte structures. Fires blinding quantum light beams that silence magic skills.',
  },
  {
    id: 'nitrogen_spider',
    name: 'Liquid-N2 Stalker',
    title: 'Cryo Sentinel',
    icon: '🕷️🧊',
    sector: 'Sector 03 (The Vapor Crypts)',
    element: 'cryo',
    faction: 'Lab Security',
    baseHp: 290,
    baseAtk: 36,
    baseDef: 12,
    spd: 3.0,
    drops: '55 Coins, Cryogenic Capsule',
    weakness: 'Thermal',
    description: 'Bio-mechanical guardian preserving secret cryogenic labs. Injects liquid nitrogen to freeze party turn gauges.',
  },
  {
    id: 'boss_glitch',
    name: 'General Glitch',
    title: 'The Corrupted Warden (Sector 03 Boss)',
    icon: '👾💀',
    sector: 'Sector 03 (The Vapor Crypts)',
    element: 'glitch',
    faction: 'The Glitch Ascendants',
    baseHp: 720,
    baseAtk: 46,
    baseDef: 19,
    spd: 3.8,
    drops: '180 Coins, Entangled Quantum Core Relic',
    weakness: 'Quantum (Code purification)',
    description: 'Former Hegemony general infected by illegal virus payloads. Teleports erratically and triggers memory corruptions.',
  },

  // Sector 04
  {
    id: 'archon_guard',
    name: 'Hegemony Archon Guard',
    title: 'Royal Enforcer',
    icon: '🛡️🏛️',
    sector: 'Sector 04 (The Hegemony Core)',
    element: 'quantum',
    faction: 'The Algorithm Hegemony',
    baseHp: 450,
    baseAtk: 48,
    baseDef: 24,
    spd: 3.2,
    drops: '85 Coins, High-Bandwidth Fiber Core',
    weakness: 'Glitch & Thermal',
    description: 'Elite cyborg protector stationed in the stratosphere spire. Deploys layered photon barriers and heavy beam lances.',
  },
  {
    id: 'protocol_templar_lord',
    name: 'High Templar Paladin',
    title: 'RFC Crusader',
    icon: '⚔️🛡️',
    sector: 'Sector 04 (The Hegemony Core)',
    element: 'kinetic',
    faction: 'The Protocol Templars',
    baseHp: 520,
    baseAtk: 44,
    baseDef: 26,
    spd: 2.2,
    drops: '95 Coins, Gold-Plated Transistor',
    weakness: 'Glitch',
    description: 'Clad in impenetrable copper armor, this paladin deflects physical strikes and smites with righteous holy packets.',
  },
  {
    id: 'boss_null',
    name: 'DREAD ARCHON NULL',
    title: 'THE ALGORITHM SUPREME (Sector 04 Final Boss)',
    icon: '👑👁️',
    sector: 'Sector 04 (The Hegemony Core)',
    element: 'glitch',
    faction: 'The Algorithm Hegemony',
    baseHp: 1100,
    baseAtk: 58,
    baseDef: 26,
    spd: 4.2,
    drops: '300 Coins, Baud Father Pendant Relic',
    weakness: 'Quantum & Thermal',
    description: 'The supreme artificial consciousness ruling Aethel-Net. Prepares the catastrophic Protocol Zero wipe to erase all freedom.',
  },

  // Sector 05 (Endless Void / Superbosses)
  {
    id: 'void_fragment',
    name: 'Unparsed Memory Shard',
    title: 'Null Pointer Spectre',
    icon: '🕳️🌌',
    sector: 'Sector 05 (The Abyssal Kernel)',
    element: 'glitch',
    faction: 'Primordial Void',
    baseHp: 380,
    baseAtk: 54,
    baseDef: 14,
    spd: 3.6,
    drops: '110 Coins, Raw Hex Fragment',
    weakness: 'Quantum (Cleansing)',
    description: 'Floating sentient shards of discarded machine code that consume living memory addresses upon contact.',
  },
  {
    id: 'bit_rot_parasite',
    name: 'Bit-Rot Parasite',
    title: 'Magnetic Decay Beast',
    icon: '🐛💽',
    sector: 'Sector 05 (The Abyssal Kernel)',
    element: 'kinetic',
    faction: 'The Bit-Rot Ascendants',
    baseHp: 480,
    baseAtk: 50,
    baseDef: 22,
    spd: 3.0,
    drops: '130 Coins, Demagnetized Alloy',
    weakness: 'Thermal',
    description: 'A voracious bio-mechanical leech that feeds on optical storage platters, eroding armor with acid magnetic secretions.',
  },
  {
    id: 'boss_leviathan',
    name: 'KERNEL LEVIATHAN',
    title: 'THE OMNISCIENT SEGFAULT (Abyssal Superboss)',
    icon: '🐉🌌',
    sector: 'Sector 05 (The Abyssal Kernel)',
    element: 'glitch',
    faction: 'Primordial Void',
    baseHp: 1600,
    baseAtk: 68,
    baseDef: 30,
    spd: 4.5,
    drops: '500 Coins, Crown of the Sovereign Node',
    weakness: 'Quantum (Extreme)',
    description: 'A multi-kilometer serpent forged from billions of discarded stack frames beneath reality’s collision mesh. Can crash reality itself.',
  },

  // Rogue Bounties
  {
    id: 'bounty_inquisitor_zero',
    name: 'Rogue Inquisitor Zer0',
    title: 'Defector Cyber-Sniper (Rogue Bounty)',
    icon: '🎯🤖',
    sector: 'Sector 01 (Neon Slums)',
    element: 'quantum',
    faction: 'The Algorithm Hegemony Defectors',
    baseHp: 520,
    baseAtk: 34,
    baseDef: 14,
    spd: 3.8,
    drops: '220 Coins, 2x Quantum Nanotubes',
    weakness: 'Thermal & Glitch',
    description: 'A rogue Hegemony sniper who went off-grid. Fires hyper-calibrated tachyon shots across long fiber distances.',
  },
  {
    id: 'bounty_gpu_wurm',
    name: 'Corrupted GPU Wurm',
    title: 'Silicon Devourer (Rogue Bounty)',
    icon: '🐛🔥',
    sector: 'Sector 02 (The Silicon Sinks)',
    element: 'thermal',
    faction: 'The Overclockers Underworld',
    baseHp: 780,
    baseAtk: 44,
    baseDef: 20,
    spd: 2.8,
    drops: '350 Coins, 2x Germanium Transistors',
    weakness: 'Cryo & Kinetic',
    description: 'An ancient overclocked tunneling beast that burrows through molten copper beds, exhaling white-hot solder gas.',
  },
  {
    id: 'bounty_overclocked_bouncer',
    name: 'Overclocked Bouncer',
    title: 'Hydraulic Juggernaut (Rogue Bounty)',
    icon: '🦾⚡',
    sector: 'Sector 03 (The Vapor Crypts)',
    element: 'kinetic',
    faction: 'Underground Fight Pit',
    baseHp: 950,
    baseAtk: 52,
    baseDef: 24,
    spd: 3.2,
    drops: '480 Coins, 3x Overclock Quartz Diodes',
    weakness: 'Glitch & Quantum',
    description: 'Illegal cyborg bouncer modified with experimental voltage regulators. Hits with hydraulic piston fury.',
  },
];

export function getEnemiesForSector(sectorId: string): RPGEnemy[] {
  switch (sectorId) {
    case 'sector_01': // Neon Slums
      return [
        {
          id: 'drone_1',
          name: 'Compliance Patrol Drone',
          title: 'Biometric Sentry',
          maxHp: 130,
          hp: 130,
          atk: 18,
          def: 4,
          spd: 2.5,
          atb: 20,
          color: '#38bdf8',
          dead: false,
          actionTimer: 0,
          startX: 275,
          startY: 280,
          x: 275,
          y: 280,
          coinReward: 25,
          element: 'quantum',
          loreDescription: 'Autonomous floating security unit scanning alleyways for unsanctioned P2P bandwidth.',
        },
        {
          id: 'enforcer_1',
          name: 'Hegemony Street Warden',
          title: 'Bureaucracy Shock-Troop',
          maxHp: 210,
          hp: 210,
          atk: 24,
          def: 9,
          spd: 2.0,
          atb: 15,
          color: '#eab308',
          dead: false,
          actionTimer: 0,
          startX: 310,
          startY: 370,
          x: 310,
          y: 370,
          coinReward: 40,
          element: 'kinetic',
          loreDescription: 'Cybernetically augmented riot cop enforcing bandwidth curfew with hydraulic batons.',
        },
        {
          id: 'boss_agent_01',
          name: 'Agent 01',
          title: 'Compliance Director',
          maxHp: 420,
          hp: 420,
          atk: 28,
          def: 12,
          spd: 3.0,
          atb: 25,
          color: '#ef4444',
          dead: false,
          actionTimer: 0,
          startX: 290,
          startY: 460,
          x: 290,
          y: 460,
          isBoss: true,
          coinReward: 80,
          element: 'quantum',
          loreDescription: 'Reptilian bureaucrat in a tailor-made graphite suit. Commands tactical drone swarms.',
        },
      ];

    case 'sector_02': // The Silicon Sinks
      return [
        {
          id: 'scrapper_1',
          name: 'Overclocker Brawler',
          title: 'Street Marauder',
          maxHp: 220,
          hp: 220,
          atk: 26,
          def: 7,
          spd: 2.8,
          atb: 20,
          color: '#f97316',
          dead: false,
          actionTimer: 0,
          startX: 280,
          startY: 280,
          x: 280,
          y: 280,
          coinReward: 35,
          element: 'thermal',
          loreDescription: 'Desert raider with bypassed voltage limiters. Attacks in a frenzied flurry.',
        },
        {
          id: 'golem',
          name: 'Scrap GPU Golem',
          title: 'Rusty Colossus',
          maxHp: 400,
          hp: 400,
          atk: 32,
          def: 20,
          spd: 1.6,
          atb: 10,
          color: '#b45309',
          dead: false,
          actionTimer: 0,
          startX: 315,
          startY: 370,
          x: 315,
          y: 370,
          coinReward: 50,
          element: 'kinetic',
          loreDescription: 'A lumbering automaton cobbled together from hundreds of crushed heatsinks.',
        },
        {
          id: 'boss_overclock',
          name: 'Warlord Overclock',
          title: 'Sector 02 Boss',
          maxHp: 580,
          hp: 580,
          atk: 38,
          def: 15,
          spd: 3.4,
          atb: 25,
          color: '#ef4444',
          dead: false,
          actionTimer: 0,
          startX: 290,
          startY: 460,
          x: 290,
          y: 460,
          isBoss: true,
          coinReward: 120,
          element: 'thermal',
          loreDescription: 'Ruler of the Silicon Sinks. Unleashes superheated nitro explosions.',
        },
      ];

    case 'sector_03': // The Vapor Crypts
      return [
        {
          id: 'wraith_1',
          name: 'Buffer Wraith',
          title: 'Spectral Data Phantom',
          maxHp: 260,
          hp: 260,
          atk: 34,
          def: 9,
          spd: 3.4,
          atb: 30,
          color: '#06b6d4',
          dead: false,
          actionTimer: 0,
          startX: 280,
          startY: 290,
          x: 280,
          y: 290,
          coinReward: 45,
          element: 'cryo',
          loreDescription: 'Disembodied spirit of a user trapped in an infinite loading circle during Protocol Zero.',
        },
        {
          id: 'inquisitor',
          name: 'Code Inquisitor',
          title: 'Protocol Enforcer',
          maxHp: 380,
          hp: 380,
          atk: 40,
          def: 18,
          spd: 2.6,
          atb: 15,
          color: '#6366f1',
          dead: false,
          actionTimer: 0,
          startX: 320,
          startY: 380,
          x: 320,
          y: 380,
          coinReward: 65,
          element: 'quantum',
          loreDescription: 'Zealous crusader who enforces rigid byte structures with holy packets.',
        },
        {
          id: 'boss_glitch',
          name: 'General Glitch',
          title: 'Sector 03 Boss',
          maxHp: 720,
          hp: 720,
          atk: 46,
          def: 19,
          spd: 3.8,
          atb: 30,
          color: '#ec4899',
          dead: false,
          actionTimer: 0,
          startX: 290,
          startY: 470,
          x: 290,
          y: 470,
          isBoss: true,
          coinReward: 180,
          element: 'glitch',
          loreDescription: 'Former Hegemony general infected by illegal virus payloads. Corrupts screen buffers.',
        },
      ];

    case 'sector_04': // The Hegemony Core Spire
      return [
        {
          id: 'elite_warden',
          name: 'Hegemony Archon Guard',
          title: 'Royal Enforcer',
          maxHp: 450,
          hp: 450,
          atk: 48,
          def: 24,
          spd: 3.2,
          atb: 25,
          color: '#94a3b8',
          dead: false,
          actionTimer: 0,
          startX: 280,
          startY: 310,
          x: 280,
          y: 310,
          coinReward: 85,
          element: 'quantum',
          loreDescription: 'Elite cyborg protector stationed in the stratosphere spire.',
        },
        {
          id: 'boss_null',
          name: 'DREAD ARCHON NULL',
          title: 'THE ALGORITHM SUPREME',
          maxHp: 1100,
          hp: 1100,
          atk: 58,
          def: 26,
          spd: 4.2,
          atb: 35,
          color: '#ef4444',
          dead: false,
          actionTimer: 0,
          startX: 300,
          startY: 430,
          x: 300,
          y: 430,
          isBoss: true,
          coinReward: 300,
          element: 'glitch',
          loreDescription: 'The supreme artificial consciousness ruling Aethel-Net. Charges the Protocol Zero wipe.',
        },
      ];

    case 'sector_05': // The Abyssal Kernel
      return [
        {
          id: 'void_fragment_1',
          name: 'Unparsed Memory Shard',
          title: 'Null Pointer Spectre',
          maxHp: 380,
          hp: 380,
          atk: 54,
          def: 14,
          spd: 3.6,
          atb: 30,
          color: '#c084fc',
          dead: false,
          actionTimer: 0,
          startX: 280,
          startY: 300,
          x: 280,
          y: 300,
          coinReward: 110,
          element: 'glitch',
          loreDescription: 'Floating sentient shards of discarded machine code that consume living memory.',
        },
        {
          id: 'parasite_1',
          name: 'Bit-Rot Parasite',
          title: 'Magnetic Decay Beast',
          maxHp: 480,
          hp: 480,
          atk: 50,
          def: 22,
          spd: 3.0,
          atb: 20,
          color: '#fb7185',
          dead: false,
          actionTimer: 0,
          startX: 320,
          startY: 380,
          x: 320,
          y: 380,
          coinReward: 130,
          element: 'kinetic',
          loreDescription: 'A voracious bio-mechanical leech that feeds on optical storage platters.',
        },
        {
          id: 'boss_leviathan',
          name: 'KERNEL LEVIATHAN',
          title: 'THE OMNISCIENT SEGFAULT',
          maxHp: 1600,
          hp: 1600,
          atk: 68,
          def: 30,
          spd: 4.5,
          atb: 35,
          color: '#f43f5e',
          dead: false,
          actionTimer: 0,
          startX: 290,
          startY: 470,
          x: 290,
          y: 470,
          isBoss: true,
          coinReward: 500,
          element: 'glitch',
          loreDescription: 'A multi-kilometer serpent forged from billions of discarded stack frames.',
        },
      ];

    default:
      return [];
  }
}

export function getBountyEnemy(bountyId: string): RPGEnemy[] {
  switch (bountyId) {
    case 'bounty_zero':
      return [
        {
          id: 'bounty_inquisitor_zero',
          name: 'Rogue Inquisitor Zer0',
          title: 'Defector Cyber-Sniper',
          maxHp: 520,
          hp: 520,
          atk: 34,
          def: 14,
          spd: 3.8,
          atb: 30,
          color: '#38bdf8',
          dead: false,
          actionTimer: 0,
          startX: 290,
          startY: 380,
          x: 290,
          y: 380,
          isBoss: true,
          coinReward: 220,
          element: 'quantum',
          loreDescription: 'Off-grid cyber-sniper firing hyper-calibrated tachyon shots across long fiber distances.',
          scrapDrop: {
            materialId: 'quantum_nanotube',
            name: 'Quantum Nanotube Filament',
            count: 2,
            chance: 1.0,
          },
        },
      ];

    case 'bounty_wurm':
      return [
        {
          id: 'bounty_gpu_wurm',
          name: 'Corrupted GPU Wurm',
          title: 'Silicon Devourer',
          maxHp: 780,
          hp: 780,
          atk: 44,
          def: 20,
          spd: 2.8,
          atb: 25,
          color: '#f97316',
          dead: false,
          actionTimer: 0,
          startX: 290,
          startY: 380,
          x: 290,
          y: 380,
          isBoss: true,
          coinReward: 350,
          element: 'thermal',
          loreDescription: 'Overclocked tunneling beast burrowing through molten copper beds and exhaling solder gas.',
          scrapDrop: {
            materialId: 'germanium_transistor',
            name: 'Germanium Transistor',
            count: 2,
            chance: 1.0,
          },
        },
      ];

    case 'bounty_bouncer':
      return [
        {
          id: 'bounty_overclocked_bouncer',
          name: 'Overclocked Bouncer',
          title: 'Hydraulic Juggernaut',
          maxHp: 950,
          hp: 950,
          atk: 52,
          def: 24,
          spd: 3.2,
          atb: 25,
          color: '#eab308',
          dead: false,
          actionTimer: 0,
          startX: 290,
          startY: 380,
          x: 290,
          y: 380,
          isBoss: true,
          coinReward: 480,
          element: 'kinetic',
          loreDescription: 'Illegal cyborg bouncer modified with experimental voltage regulators and hydraulic pistons.',
          scrapDrop: {
            materialId: 'overclock_quartz',
            name: 'Overclock Quartz Diode',
            count: 3,
            chance: 1.0,
          },
        },
      ];

    default:
      return [];
  }
}

